server:
  port: 8761

spring:
  application:
    name: USER-SERVICE

  cloud:
    config:
      enabled: false
eureka:
  instance:
    hostname: "${HOSTNAME}.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS}

